version: '3'

services:
  mangabot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: ghcr.io/gazes-media/mangabot:main
    env_file:
      - .env
    tty: true
    restart: always
    volumes:
      - ./data/:/app/data/
