[tool.pylint]
max-line-length = 120
allow-reexport-from-package = true
ignore-patterns = [".*.pyi"]
jobs = 4
unsafe-load-any-extension = false
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "abstract-method",
    # "arguments-differ",
    # "attribute-defined-outside-init",
    # "duplicate-code",
    # "eq-without-hash",
    # "fixme",
    # "global-statement",
    # "implicit-str-concat",
    # "import-error",
    # "import-self",
    # "import-star-module-level",
    # "inconsistent-return-statements",
    # "invalid-str-codec",
]

argument-rgx = "^[a-z_][a-z0-9_]{0,30}$"
attr-rgx = "^[a-z_][a-z0-9_]{0,30}$"
function-rgx = "^[a-z_][a-z0-9_]{0,30}$"
method-rgx = '[a-z_][a-z0-9_]{0,30}$'
variable-rgx = '[a-z_][a-z0-9_]{0,30}$'

ignore-long-lines = '''(?x)(
^\s*(\#\ )?<?https?://\S+>?$|
^\s*(from\s+\S+\s+)?import\s+.+$)'''

max-module-lines = 99999
indent-string = '    '
dummy-variables-rgx = '^\*{0,2}(_$|unused_|dummy_)'
callbacks = ['cb_', '_cb']

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120
combine_as_imports = true
